"""empty message

Revision ID: 7485e844371c
Revises: 3e7cd47ca171
Create Date: 2025-04-03 03:52:31.580862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7485e844371c'
down_revision = '3e7cd47ca171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('skin_color', sa.String(length=50), nullable=False),
    sa.Column('hair_color', sa.String(length=50), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(length=50), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='character_pkey'),
    sa.UniqueConstraint('uid', name='character_uid_key')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
