"""empty message

Revision ID: fa60f24c25a2
Revises: 7485e844371c
Create Date: 2025-04-03 04:08:24.110253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa60f24c25a2'
down_revision = '7485e844371c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
